# -*- coding: utf-8 -*-
"""Análise de Recursos Humanos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1khXhdUFlZECz1URbw4BdrOX7Ust_nQnB

Por: DLeyendecer

Case de Recursos Humanos, estudo de caso abordando a gestão de recursos humanos com foco em análise de dados de renda, fundamentado em experiência.

Base de Dados

https://www.kaggle.com/datasets/karthickveerakumar/salary-data-simple-linear-regression?resource=download
"""

#libs necessarias

#libs para modelagem e matrizes
import numpy as np
import pandas as pd

#libs para analise grafica
import matplotlib.pyplot as plt
import seaborn as sns

#lib para ignorar ar avisos
import warnings

#desabilitando avisos
warnings.filterwarnings('ignore')

#lendo os dados
Base_Dados = pd.read_csv('Salary_Data.csv')

#verificando
Base_Dados.head()

#renomeando as colunas
Base_Dados.rename( columns={
    'YearsExperience' : 'Xp',
    'Salary' : 'Renda'
}, inplace=True)

#dimensao
Base_Dados.shape

#campos nulos
Base_Dados.isnull().sum()

#grafico nulos
sns.heatmap(Base_Dados.isnull(),cbar=False);

Base_Dados.describe()

plt.figure(figsize=(10,6))
plt.title('Análise de Renda')
sns.kdeplot(Base_Dados['Renda'], color='green');

plt.figure(figsize=(10,6))
plt.title('Análise da XP')
sns.kdeplot(Base_Dados['Xp'],color='blue');

#distribuicao
plt.figure(figsize=(10, 5))
sns.boxplot(Base_Dados['Renda']);

#distribuicao
plt.figure(figsize=(10, 5))
sns.boxplot(Base_Dados['Xp']);

#distribuicao
plt.figure(figsize=(10,5))
sns.scatterplot(data=Base_Dados, x='Renda', y='Xp');

#distribuicao
plt.figure(figsize=(10,5))
sns.regplot(data=Base_Dados, x='Renda', y='Xp');

#correlacao
correlacao = Base_Dados.corr('pearson')
plt.figure(figsize=(10,5))
sns.heatmap(correlacao, annot=True, cbar=True);

#correlacao
correlacao = Base_Dados.corr('spearman')
plt.figure(figsize=(10,5))
sns.heatmap(correlacao, annot=True, cbar=True);